wandb_version: 1

algorithm:
  value: geneticSingle
depthBounds:
  value:
  - 5
  - 300
eliteSize:
  value: 3
fidelity:
  value: 0.95
maxIterations:
  value: 50
monetaryLimit:
  value: 5000000
mutationRate:
  value: 0.15873064757902794
noise:
  value: 0.5
numGenerations:
  value: 195
populationSize:
  value: 123
seed:
  value: 42
smoothness:
  value: 0.5
terrainSize:
  value: 400
timeLimit:
  value: 500000
tournamentSize:
  value: 6
volumeBounds:
  value:
  - 10
  - 500000
