wandb_version: 1

algorithm:
  value: genetic
depthBounds:
  value:
  - 5
  - 300
eliteSize:
  value: 2
fidelity:
  value: 0.95
maxIterations:
  value: 50
monetaryLimit:
  value: 5000000
mutationRate:
  value: 0.10923411213417174
noise:
  value: 0.5
numGenerations:
  value: 123
populationSize:
  value: 169
seed:
  value: 42
smoothness:
  value: 0.5
terrainSize:
  value: 400
timeLimit:
  value: 500000
tournamentSize:
  value: 4
volumeBounds:
  value:
  - 10
  - 500000
