wandb_version: 1

algorithm:
  value: genetic
depthBounds:
  value:
  - 5
  - 300
eliteSize:
  value: 4
fidelity:
  value: 0.95
maxIterations:
  value: 50
monetaryLimit:
  value: 5000000
mutationRate:
  value: 0.1186871004153193
noise:
  value: 0.5
numGenerations:
  value: 276
populationSize:
  value: 205
seed:
  value: 42
smoothness:
  value: 0.5
terrainSize:
  value: 400
timeLimit:
  value: 500000
tournamentSize:
  value: 2
volumeBounds:
  value:
  - 10
  - 500000
