wandb_version: 1

algorithm:
  value: genetic
depthBounds:
  value:
  - 5
  - 300
eliteSize:
  value: 3
fidelity:
  value: 0.95
maxIterations:
  value: 50
monetaryLimit:
  value: 5000000
mutationRate:
  value: 0.10246367391953257
noise:
  value: 0.5
numGenerations:
  value: 154
populationSize:
  value: 232
seed:
  value: 42
smoothness:
  value: 0.5
terrainSize:
  value: 400
timeLimit:
  value: 500000
tournamentSize:
  value: 2
volumeBounds:
  value:
  - 10
  - 500000
