wandb_version: 1

algorithm:
  value: greedy
depthBounds:
  value:
  - 5
  - 30
eliteSize:
  value: 4
fidelity:
  value: 0.95
maxIterations:
  value: 50
monetaryLimit:
  value: 5000000
mutationRate:
  value: 0.15
noise:
  value: 0.5
numGenerations:
  value: 200
populationSize:
  value: 50
seed:
  value: 42
smoothness:
  value: 0.5
terrainSize:
  value: 400
timeLimit:
  value: 500000
tournamentSize:
  value: 6
volumeBounds:
  value:
  - 10
  - 500
